ImgLazyLoading:
  severity: error
ValidHTMLTranslation:
  severity: error
MatchingTranslations:
  enabled: false
SchemaJsonFormat:
  severity: suggestion
TemplateLength:
  enabled: true
  severity: suggestion
  max_length: 1000
ImgLazyLoading:
  severity: error